### ISSUE TITLE
State

### ISSUE THREAD

**Issue by legodude17** [getify/FoilScript#2]
Are you still working on this? Do you want to look into build a compiler for this? The compiler won't be able to solve all of these directly as a lot of these are actually engine changes.

**Comment by getify** [comment]
It is not under active development. I still have notions that someday I'll invent my own language, but that's a long-term research project. Some of the ideas I sketched out here would probably make it into such a language, but my current interests would lead me to design a language primarily based on how easy it would be to learn.
